Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,31 +8,51 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout
-      uses: actions/checkout@v4
+      - name: Checkout
+        uses: actions/checkout@v4
 
-    - name: Setup Java
-      uses: actions/setup-java@v4
-      with:
-        distribution: "temurin"
-        java-version: "17"
+      - name: Setup Java
+        uses: actions/setup-java@v4
+        with:
+          distribution: "temurin"
+          java-version: "17"
 
-    - name: Get latest commit hash
-      id: latest_commit
-      run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
+      - name: Get latest commit hash
+        id: latest_commit
+        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
-    - name: Build APK
-      run: |
-        bash build.sh release
+      - name: Build APK
+        run: |
+          bash build.sh release
 
-    - name: Upload build artifact
-      uses: actions/upload-artifact@v4
-      with:
-        name: TrebleApp
-        path: TrebleApp.apk
+      - name: Upload build artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: TrebleApp
+          path: TrebleApp.apk
 
-    - name: Update APK
-      run: |
-        git add TrebleApp/app.apk
-        git commit -m "Up TrebleApp to Doze-off/treble_app@${{ steps.latest_commit.outputs.hash }}"
-        git push origin pie || true
+      - name: Push APK to Doze-off/treble_app
+        run: |
+          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
+          git config --global user.name "github-actions[bot]"
+
+          git clone https://${{ secrets.DOZEOFF_TOKEN }}@github.com/Doze-off/treble_app
+          cd treble_app
+          git checkout pie
+          mkdir -p TrebleApp
+          cp ../TrebleApp.apk TrebleApp/app.apk
+          git add TrebleApp/app.apk
+          git commit -m "Up TrebleApp to Doze-off/treble_app@${{ steps.latest_commit.outputs.hash }}" || echo "No changes"
+          git push origin pie || echo "Push failed (likely no changes)"
+          cd ..
+
+      - name: Push APK to Doze-off/vendor_hardware_overlay
+        run: |
+          git clone https://${{ secrets.DOZEOFF_TOKEN }}@github.com/Doze-off/vendor_hardware_overlay
+          cd vendor_hardware_overlay
+          git checkout pie
+          mkdir -p TrebleApp
+          cp ../TrebleApp.apk TrebleApp/app.apk
+          git add TrebleApp/app.apk
+          git commit -m "Up TrebleApp to Doze-off/treble_app@${{ steps.latest_commit.outputs.hash }}" || echo "No changes"
+          git push origin pie || echo "Push failed (likely no changes)"
