Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,15 +15,17 @@ jobs:
         uses: actions/setup-java@v4
         with:
           distribution: "temurin"
-          java-version: "24"
+          java-version: "17"
 
       - name: Get latest commit hash
         id: latest_commit
         run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
+      - name: Make build.sh executable
+        run: chmod +x build.sh
+
       - name: Build APK
-        run: |
-          bash build.sh release
+        run: ./build.sh release
 
       - name: Upload build artifact
         uses: actions/upload-artifact@v4
@@ -35,7 +37,6 @@ jobs:
         run: |
           git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --global user.name "github-actions[bot]"
-
           git clone https://${{ secrets.DOZEOFF_TOKEN }}@github.com/Doze-off/treble_app
           cd treble_app
           git checkout pie
@@ -56,3 +57,4 @@ jobs:
           git add TrebleApp/app.apk
           git commit -m "Up TrebleApp to Doze-off/treble_app@${{ steps.latest_commit.outputs.hash }}" || echo "No changes"
           git push origin pie || echo "Push failed (likely no changes)"
+ie || echo "Push failed (likely no changes)"
